const authTypes = {
    POST_USER_REQUEST: "POST_USER_REQUEST",
    POST_USER_RESPONSE: "POST_USER_RESPONSE",
    POST_USER_RES_CLEAR: "POST_USER_RES_CLEAR",

    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_RESPONSE: "LOGIN_RERESPONSE",
    LOGIN_RES_CLEAR: "LOGIN_RES_CLEAR",

    ACTIVE_USER_REQUEST: "ACTIVE_USER_REQUEST",
    ACTIVE_USER_RESPONSE: "ACTIVE_USER_RESPONSE",
    CLEAR_ACTIVE_USER: "CLEAR_ACTIVE_USER",

    ERROR_RESPONSE: "ERROR_RESPONSE",
    CLEAR_ERROR_RESPONSE: "CLEAR_ERROR_RESPONSE"
}
export default authTypes;